"""Bazel module for Scala Redef."""

module(
    name = "scala_redef",
    version = "0.0.0",
)

bazel_dep(name = "rules_scala", version = "7.2.6")
bazel_dep(name = "rules_java", version = "9.6.1")
bazel_dep(name = "rules_jvm_external", version = "7.1")

scala_config = use_extension(
    "@rules_scala//scala/extensions:config.bzl",
    "scala_config",
)
scala_config.settings(scala_version = "3.8.4")

scala_deps = use_extension(
    "@rules_scala//scala/extensions:deps.bzl",
    "scala_deps",
)
scala_deps.scala()

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "com.lihaoyi:utest_3:0.10.0-RC1",
        "org.scala-lang:scaladoc_3:3.8.4",
        "org.scalacheck:scalacheck_3:1.19.0",
    ],
    fail_if_repin_required = True,
    known_contributing_modules = ["protobuf"],
    lock_file = "//:maven_install.json",
    repositories = ["https://repo1.maven.org/maven2"],
)
use_repo(maven, "maven")
